security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: database_users
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: trick_list
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: security_logout
                target: trick_list

    access_control:
        - { path: ^/profile,          roles: ROLE_USER }
        - { path: ^/trick/create,     roles: ROLE_USER }
        - { path: ^/trick/edit,       roles: ROLE_USER }
        - { path: ^/trick/delete,     roles: ROLE_USER }
        - { path: ^/category/create,  roles: ROLE_USER }
        - { path: ^/category/delete,  roles: ROLE_USER }
        - { path: ^/change-password,  roles: ROLE_USER }
