language: php
sudo: false
php:
  - '7.1'

env:
  global:
    - LC_ALL=en_US.UTF-8

script:
   - composer install
   - php bin/console doctrine:schema:create --env=test
   - php bin/console doctrine:fixtures:load --env=test
   - php bin/phpunit
